language: ruby
rvm:
  - 2.6.3

cache: bundler

install: bundle install
script: jekyll build

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "GVZlbzTejDB45FOT4xaCuQBV61VmBai1eTjYL67xGnaXFjN2BLbc9qBmFeXmzUq8Vqop+5bljNqF0rZXR/OtcRP0ke2ZijZ5ltDGFhOTO3pTIPrKah8kPe6Vafrph9dUQasBmgrZp0zGbj7NVx6PjNs7pYf8vJCHWIUa5aXV2cdlS2pYI57w8X2cS2WohquihO2FbgkNKimlValIt7gFsWXJB92kmne8GAwQDSFu4ILfXshoZFqrCG3MGu53PPK9ZLoUu39bajTCNyfUuE4BL1mPOaInLmnfpBRpEfRJX0nVNAD2Xop7ocsaKYEKUHYudXFN0PdQJ2rc9SnC7xooQ6fRE5vTrEyFrAIzjYe7J95bPCeK/KYihHMz/iRt69rlVmkW60agDGD8PBgtWeS0SjnhFaKKz97hlHIMEWOh9VH050gRH10zZuF1fh+FNAddI9dfwRghGzUr0TCq0I8u6D7yNdAefCZQ438eyYt82zsD147FS4P51Qs0cXuXkVVIVn4hsD+8C2Gw9qIUWEl3og0IZKNjzebANk9t6TKzLLoDu1bWRAno5ZPo9pwz760knVy2tA4+EtR4CvO5ozOIeVV0nTVfPQnqv/b7VaGyX+dFbBbQ2cL94Tu2CoEeacLlUBA4wC2CFAs+pMwspcUXSY+N5xKpkXnGvmJ9lBmwGr4="
  on:
    branch: master

env:
 - JEKYLL_ENV=production