language: ruby
rvm:
  - 2.5.1

cache: bundler

install: bundle install
script: jekyll build

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "4dBtPre6KwoTTCKkKuDuyJT5Vnrm0r1Q5xPkMo7jhAoqVHASsekBtUMDdDoMfG79dbU7Ua127R44o+7coMQYNZW7ISYwls0yu94/4lBtAcv4Agx03rc55WYdN/WxdLMn5X3dSx8H9mwoFvbpJ30IP+rdbcelb86xz+miw+u5COMKLi8Y5fqIk8InmfFrPXNnafoiRVNyC7U6ZA+pXXUV7DjggQdcyv9VEYwxiUTw2KejCq2lm4OWYQ64JeN9bGk6vqasZlLwYJPuFutUyw4LEdwsHGSE8+1dsY4/KOsWjIwsuZsoDr6UsFlx00+oAVm/9PP4PRkoIL/YqdO3JYRPEaC/+pEw/QYlht9YMs45Jeb1Pxd14UtGfyUXSFPP5BDnDUEmpapEHMYdaEMIo5uhMVi34/2+B6pIpIXR5UQ6lnIdIKuy5TkZ4lU/qNJCk15tRy6b4MVNAMQCZJXO7rhLFHNPUwySkVrtvhHCJd1k6qpx1R58G+N3Ik3q87x1zKPQol3ZE6H6VQLbd/xBYJJokQEtUdg8LfRh2Yqs1SFpkjTpk6Tbh9dxM8J0n2lxIIURWYL4K37Wfv1RERWq+cwX0A9iuT6bdCCrN5AZBeaAsMv4N8UikE1TzbMU9nOg/DKXs2WYgBq6dZ+0MK6SMGexPLhVpKH3WngXXeT9tYFrWnw="
  on:
    branch: master

env:
 - JEKYLL_ENV=production